name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: ./gradlew test --info
